# Default values for podinfo.

replicaCount: 1
logLevel: info
backend: #http://backend-podinfo:9898/echo
backends: []

ui:
  color: "#34577c"
  message: ""
  logo: ""

faults:
  delay: false
  error: false
  unhealthy: false
  unready: false
  testFail: false
  testTimeout: false

h2c:
  enabled: false

image:
  repository: eu.gcr.io/dbk-ecom-cicd/podinfo
  tag: 3.2.4
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  metricsPort: 9797
  httpPort: 9898
  externalPort: 9898
  grpcPort: 9999
  grpcService: podinfo
  nodePort: 31198

# metrics-server add-on required
hpa:
  enabled: false
  maxReplicas: 10
  # average total CPU usage per pod (1-100)
  cpu:
  # average memory usage per pod (100Mi-1Gi)
  memory:
  # average http requests per second per pod (k8s-prometheus-adapter)
  requests:

serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

linkerd:
  profile:
    enabled: false

serviceMonitor:
  enabled: false
  interval: 15s

ingress:
  enabled: true
  annotations: {
    kubernetes.io/tls-acme: "true",
    kubernetes.io/ingress.class: "internal"
    }
  path: /
  hosts:
    - podinfo-sit.dev-debijenkorf.nl
    - podinfo-sit.dev-debijenkorf.be
    - podinfo-sit.dev-debijenkorf.de
  tls:
    - secretName: podinfo-sit-tls
      hosts:
        - podinfo-sit.dev-debijenkorf.nl
        - podinfo-sit.dev-debijenkorf.be
        - podinfo-sit.dev-debijenkorf.de
  
resources:
  limits:
  requests:
    cpu: 1m
    memory: 16Mi

nodeSelector: {}

tolerations: []

affinity: {}

